### ISSUE TITLE
BUG: New Dagre graphs breaks code

### ISSUE THREAD

**Issue by JoshuaRVONQ** [techniq/layerchart#298]
With the new release https://github.com/techniq/layerchart/releases/tag/layerchart%400.60.0 we are experiencing compile errors:

```
frontend-1  |   VITE v5.4.11  ready in 1075 ms
frontend-1  | 
frontend-1  |   ➜  Local:   https://localhost:5173/
frontend-1  |   ➜  Network: https://172.40.1.4:5173/
frontend-1  | ✘ [ERROR] /srv/app/node_modules/.pnpm/layerchart@0.60.0_svelte@4.2.19_typescript@5.7.2/node_modules/layerchart/dist/components/Dagre.svelte:2:9 Unexpected token [plugin vite-plugin-svelte:optimize-svelte]
frontend-1  | 
frontend-1  |     node_modules/.pnpm/layerchart@0.60.0_svelte@4.2.19_typescript@5.7.2/node_modules/layerchart/dist/components/Dagre.svelte:2:9:
frontend-1  |       2 │  export type DagreGraphData = {
frontend-1  |         ╵          ^
frontend-1  | 
frontend-1  |   The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import
frontend-1  | 
frontend-1  |     node_modules/.pnpm/layerchart@0.60.0_svelte@4.2.19_typescript@5.7.2/node_modules/layerchart/dist/components/index.js:20:33:
frontend-1  |       20 │ export { default as Dagre } from './Dagre.svelte';
frontend-1  |          ╵                                  ~~~~~~~~~~~~~~~~
frontend-1  | 
frontend-1  | /srv/app/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1472
frontend-1  |   let error = new Error(text);
frontend-1  |               ^
frontend-1  | 
frontend-1  | Error: Build failed with 1 error:
frontend-1  | node_modules/.pnpm/layerchart@0.60.0_svelte@4.2.19_typescript@5.7.2/node_modules/layerchart/dist/components/Dagre.svelte:2:9: ERROR: [plugin: vite-plugin-svelte:optimize-svelte] /srv/app/node_modules/.pnpm/layerchart@0.60.0_svelte@4.2.19_typescript@5.7.2/node_modules/layerchart/dist/components/Dagre.svelte:2:9 Unexpected token
frontend-1  |     at failureErrorWithLog (/srv/app/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1472:15)
frontend-1  |     at /srv/app/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:945:25
frontend-1  |     at /srv/app/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1353:9
frontend-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
frontend-1  |   errors: [Getter/Setter],
frontend-1  |   warnings: [Getter/Setter]
frontend-1  | }
frontend-1  | 
frontend-1  | Node.js v22.12.0
frontend-1  |  ELIFECYCLE  Command failed with exit code 1.
frontend-1  | Lockfile is up to date, resolution step is skipped
frontend-1  | Already up to date
frontend-1  | 
frontend-1  | Done in 673ms
```
In development build. In production build we get the error the the code is missing a `lang="ts"` on the module part. When we remove the module part, and make it normal Javascript code, and combine the two javascript sections to one, it all works.

We are working with typescript javascript. So could it be that is the problem here?

Before version 0.60 it was all working. With the new Dagre graphs we experience the above error.

What are we doing wrong? How to fix this? 
Hoe can we process the module correctly? https://github.com/techniq/layerchart/blob/e23d7d9d1cf8bc8d12bb1818da9ec1f9ca858935/packages/layerchart/src/lib/components/Dagre.svelte#L1

during production build we get the error:

```
[vite-plugin-svelte] [plugin vite-plugin-svelte] node_modules/.pnpm/layerchart@0.60.0_svelte@4.2.19_typescript@5.7.2/node_modules/layerchart/dist/components/Dagre.svelte (2:9): /app/node_modules/.pnpm/layerchart@0.60.0_svelte@4.2.19_typescript@5.7.2/node_modules/layerchart/dist/components/Dagre.svelte:2:9 Unexpected token"
- Did you forget to add lang="ts" to your script tag?"
 ```

**Comment by techniq** [comment]
Awe, interesting this didn't show up in CI/CD but I think it is because you are on Svelte 4 and the docs/build are on Svelte 5.

The main issue is the use of `<script module>` instead of `<script context="module">` (a change from Svelte 4 => 5), but was also missing `lang="ts"`.  Still odd this didn't show up locally or in CI, but should be [fixed](https://github.com/techniq/layerchart/commit/bfed78593b58fbbe000722701d89c3b81005ed8c#diff-cc4fba44a82a7dba3243b4eeb828a812f1290306d4819a4ce893e042d3dd2f48L1) in [0.60.1](https://github.com/techniq/layerchart/releases/tag/layerchart%400.60.1)

**Comment by JoshuaRVONQ** [comment]
Ah, nice that it can be resolved. I am not that expert in Svelte (yet). But I was not that wrong...

Thanks for the fix and I can say it is working for us!
